### ISSUE TITLE
Could Astra-sim1.0 support 3D parallism?

### ISSUE THREAD

**Issue by CavalryXD** [astra-sim/astra-sim#112]
I read the Astra-sim2.0 paper "ASTRA-sim2.0: Modeling Hierarchical Networks and Disaggregated Systems for Large-model Training at Scale" and section Motivation.A mentions that 
> The original ASTRA-sim cannot support complex parallelization strategies such as pipeline parallelism and 3D parallelism. 

So I want to ask if we can implement the based on current Astra-sim1.0 parallism in **Workload.cc**?

Take ZeRO-1 as an example, ZeRO-1 issues no communication in forward pass and issues AllReduce to synchronize gradients. Afterthat, ZeRO-1 will also issues AllGather to synchronize the updated weights by optimizer.

Therefore, can we add a new function in Workload.cc named ***iterate_3d_parallel()*** based on **iterate_data_parallel()**, in which we modify the layer states transition and issue AllGather communication(required by ZeRO-1) so that the 3D parallism is potentially supported by Astra-sim1.0?

**Comment by TaekyungHeo** [comment]
Hello, @CavalryXD. ASTRA-sim 1.0 was implemented with the assumption that all NPUs perform the same operation simultaneously. Implementing `iterate_3d_parallel()` in ASTRA-sim 1.0 would involve efforts similar to what we undertook to develop ASTRA-sim 2.0. Therefore, I would recommend using ASTRA-sim 2.0 instead of trying to implement 3D parallelism in ASTRA-sim 1.0.

**Comment by CavalryXD** [comment]
Thanks for your reply @TaekyungHeo.
I still don't understand why 3D parallism cannot be implemented in Astra-sim 1.0 although Astra-sim 1.0 assumes that all NPUs perform the same operation simultaneously. Does the 3D parallism not correspond with this assumption?
 Could you please explain a little more? Thanks!

Here are my thoughts.
3D parallism requires extra collective communications, such as AllGather. These operations are the same among all the NPUs. It doesn't like pipeline parallism, in which each node executes different stage operations at the beginning.
For example, ZeRO-1 requires additional AllGather operations based on data parallel, so all NPUs will execute same AllGather operations.

I don't know whether it can be done. If not, please let me know, thanks!
