### ISSUE TITLE
Error during compile & build ns3

### ISSUE THREAD

**Issue by taekyounghan** [astra-sim/astra-sim#122]
Hello,

I've tried following scripts
```
# For the analytical network backend
$ ./build/astra_analytical/build.sh
# For the ns3 network backend. Python2 required.
$ ./build/astra_ns3/build.sh -c
```

However, the following error occured
```
[ 753/1535] cxx: scratch/AstraSimNetwork.cc -> build/scratch/AstraSimNetwork.cc.1.o
In file included from ./ns3/AstraCongestionApi.hh:9:0,
                 from ./ns3/applications-module.h:13,
                 from ../scratch/common.h:20,
                 from ../scratch/entry.h:4,
                 from ../scratch/AstraSimNetwork.cc:6:
./ns3/EventHandlerTracker.hh:9:20: fatal error: optional: No such file or directory
compilation terminated.
```

And found that NS3's compiler is gcc, g++ 5.0 but `std::optional` is available at C++17.

Best Regards
Taekyoung

**Comment by taekyounghan** [comment]
I alternatively used `#include <boost/optional.hpp>` and changed every `std::optional` to `boost::optional` . 

Through this, the build was successful.

**Comment by jinsun-yoo** [comment]
Hi @taekyounghan ,  thanks for reporting this issue!
It seems that this is a header import issue rather than a compiler version issue. 
We have confirmed the PR fixes the issue on our side, but for added safety, could you try pulling PR #123  (branch name `import_adjustment`), _update the ns3 submodule_ and try if it works?
Once you confirm this works on your side, we will merge the fix.

**Comment by taekyounghan** [comment]
Here are my commands to build astra-sim 2.0 with PR #123 
```
git clone --recurse-submodules git@github.com:astra-sim/astra-sim.git
cd astra-sim
git pull origin pull/123/head:pr-123
git checkout pr-123

./build/astra_analytical/build.sh
[ 99%] Linking CXX executable ../bin/AstraSim_Analytical_Congestion_Aware
[ 99%] Built target AstraSim_Analytical_Congestion_Aware
[100%] Linking CXX executable ../bin/AstraSim_Analytical_Congestion_Unaware
[100%] Built target AstraSim_Analytical_Congestion_Unaware

./build/astra_ns3/build.sh -c
[ 905/1535] cxx: src/network/model/socket.cc -> build/src/network/model/socket.cc.1.o
In file included from ./ns3/AnalyticalNetwork.hh:11:0,
                 from ./ns3/applications-module.h:12,
                 from ../scratch/common.h:20,
                 from ../scratch/entry.h:4,
                 from ../scratch/AstraSimNetwork.cc:6:
./ns3/PayloadSizeTracker.hh:11:38: fatal error: topology/TopologyConfig.hh: No such file or directory
compilation terminated.
```

There's a several `#include` errors like above.

I've add CXX FLAGS -I option on `astra-sim/build/astra_ns3/build.sh` to resolve that issue 

```
CC='gcc-5' CXX="g++-5 -I${NS3_DIR}/../analytical/congestion_unaware" ./waf configure 
```

And build again, the error occurs with `optional`
```
In file included from ./ns3/AstraCongestionApi.hh:9:0,
                 from ./ns3/applications-module.h:13,
                 from ../scratch/common.h:20,
                 from ../scratch/entry.h:4,
                 from ../scratch/AstraSimNetwork.cc:6:
./ns3/EventHandlerTracker.hh:9:20: fatal error: optional: No such file or directory
compilation terminated.
```
If this build script does not import (or include) the header properly, where should I find <optional>?

I'm not sure if I did it right because I'm not used to GitHub..

Best Regards
Taekyoung

**Comment by jinsun-yoo** [comment]
Hi @taekyounghan, after checking out the `pr-123` branch, could you update the ns3 submodule before running the compile command?

So the sequence would be as follows:

```
git clone --recurse-submodules git@github.com:astra-sim/astra-sim.git
cd astra-sim
git pull origin pull/123/head:pr-123

git checkout pr-123
M       extern/network_backend/ns3
Switched to branch 'pr-123'

cd extern/network_backend/ns3/
git status
HEAD detached at 2a88fe9
nothing to commit, working tree clean

cd -
git submodule update
Submodule path 'extern/network_backend/ns3': checked out 'a46d80f9fab4d44ba687e81588c9d317ecaf3370'

cd extern/network_backend/ns3/
git status
HEAD detached at a46d80f
nothing to commit, working tree clean
```

Please check the following items: 
1) The submodule `ns3` directory is at commit `a46d80f`
2) The file `extern/network_backend/ns3/simulation/build/ns3/applications-module.h` does not contain the text `AnalyticalNetwork.hh`

Also, if it still doesn't work, try running the following command to clear temporary build files in the ns3 directory
```
cd extern/network_backend/ns3/simulation
./waf distclean
```

Best,
Jinsun

**Comment by taekyounghan** [comment]
@jinsun-yoo 

Thank you for your kind and detailed reply.

The commands you provided works perfect.

No error about including `optional` occurred while compiling (i.e., `./build/astra_ns3/build.sh -c`) 

However, there's a next error about workload file.

```
workload file: astra-sim/build/astra_ns3/../../extern/graph_frontend/chakra/et_generator/twoCompNodesDependent.0.et does not exist
```

What's strange is that there wasn't even any .et or .eg files inside that directory.

In previous attempts, I had an experience of simply changing the extension to `.et` because I had an `.eg` files.

Is there something wrong? Or should we wait a little longer for further updates?

Sincerely
Taekyoung

**Comment by jinsun-yoo** [comment]
Thank you Taekyoung for confirming this! Closing this issue :)
