### ISSUE TITLE
et_generator generates eg files

### ISSUE THREAD

**Issue by susowl** [astra-sim/astra-sim#125]
Hello!
I have found some problems in README. 
According to README i can use et_generator to generate sample traces with command:
```
$ cd ./extern/graph_frontend/chakra/et_generator
$ cmake . && make -j$(nproc)
$ ./et_generator --num_npus 64 --num_dims 1
```
And it works, but generates .eg files.
And next step:
```
# For the analytical network backend
$ cd -
$ ./build/astra_analytical/build/AnalyticalAstra/bin/AnalyticalAstra \
  --workload-configuration=./extern/graph_frontend/chakra/et_generator/twoCompNodesDependent \
  --system-configuration=./inputs/system/sample_fully_connected_sys.txt \
  --network-configuration=./inputs/network/analytical/fully_connected.json \
  --remote-memory-configuration=./inputs/remote_memory/analytical/no_memory_expansion.json
```
requires .et files as input. So it fails with error:
workload file: /home/tkhan/2-astra-sim/astra-sim/build/astra_ns3/../../extern/graph_frontend/chakra/et_generator/twoCompNodesDependent.0.et does not exist

But after just renaming *.eg files to *.et everything works as expected:
```
sys[0] finished, 10 cycles
sys[1] finished, 10 cycles
sys[2] finished, 10 cycles
sys[3] finished, 10 cycles
sys[4] finished, 10 cycles
sys[5] finished, 10 cycles
sys[6] finished, 10 cycles
...

**Comment by taekyounghan** [comment]
Hello @susowl 

With your observation, I've tried to change file extension with .et 

`rename 's/.eg/.et/' *.eg`

And it works!

However, Did you experience the error below during building process? 

https://github.com/astra-sim/astra-sim/issues/122#issuecomment-1760655723

Best Regards
Taekyoung

**Comment by susowl** [comment]
> Hello @susowl
> 
> With your observation, I've tried to change file extension with .et
> 
> `rename 's/.eg/.et/' *.eg`
> 
> And it works!
> 
> However, Did you experience the error below during building process?
> 
> [#122 (comment)](https://github.com/astra-sim/astra-sim/issues/122#issuecomment-1760655723)
> 
> Best Regards Taekyoung

I have the same problem.
