### ISSUE TITLE
No output generated by AstraSim 2.0 

### ISSUE THREAD

**Issue by susowl** [astra-sim/astra-sim#129]
Hello.

I tried Astrasim 2.0 but i can't obtain output files from it.
For example for sample:
```
# For the analytical network backend
$ cd -
$ ./build/astra_analytical/build/AnalyticalAstra/bin/AnalyticalAstra \
  --workload-configuration=./extern/graph_frontend/chakra/et_generator/twoCompNodesDependent \
  --system-configuration=./inputs/system/sample_fully_connected_sys.txt \
  --network-configuration=./inputs/network/analytical/fully_connected.json \
  --remote-memory-configuration=./inputs/remote_memory/analytical/no_memory_expansion.json
```
it generates only:
sys[62] finished, 187442108 cycles
sys[61] finished, 187442108 cycles

Adding --path=./  didn't help. 
How to receive detailed information csv files and so on(like AstraSim 1.0)?

**Comment by TaekyungHeo** [comment]
Hi @susowl ,

Thanks for trying ASTRA-sim 2.0. Currently, it mainly reports the total number of cycles. We plan to release an internal tool for computing overlap between computation and communication. Unfortunately, there aren't additional statistics available right now. Contributions to ASTRA-sim are always welcome.

**Comment by darudimimi** [comment]
Hello! Any updates about output generation?
