### ISSUE TITLE
ZeRO-3 Support 

### ISSUE THREAD

**Issue by ojewalm** [astra-sim/astra-sim#138]
I saw in the ASTRA-sim2.0 paper that an experiment was conducted with ZeRO-infinity. I would like to know the right workflow configuration options to achieve ZeRO-3 using Astra-sim.

**Comment by TaekyungHeo** [comment]
Hi @ojewalm ,

Thank you for your query regarding the ASTRA-sim2.0 paper and your interest in the ZeRO-Infinity experiment.

In the study, we focused on simulating the large-scale distributed training processes that utilize ZeRO-Infinity. For this purpose, we utilized Intel-provided Directed Acyclic Graphs (DAGs), which represent the workflow of operations under a ZeRO-Infinity setup. These DAGs, collected and provided by Intel, were then converted into Chakra Execution Traces (ETs) to be used within ASTRA-sim. This allowed us to accurately model and analyze the communication and memory optimization patterns characteristic of ZeRO-Infinity.

Regarding your interest in ZeRO-3, although we cannot share the proprietary Intel DAGs, you can approach ZeRO-3 simulations in ASTRA-sim by:

1. **Developing an ET Generator**: Craft an ET generator that models the specific behaviors of ZeRO-3, focusing on its unique memory and computation patterns within the context of NPUs.

2. **Collecting PyTorch ETs**: Alternatively, you can adapt the ET collection method in PyTorch to implement a ZeRO-3-like memory optimization strategy. By doing so, you can obtain ETs that reflect the partitioning and operation strategies of ZeRO-3, which can be fed into ASTRA-sim for performance analysis.

We're excited about your interest in replicating ZeRO-3 configurations using ASTRA-sim and look forward to any insights you might share from your experiments.
