### ISSUE TITLE
Change computation time in tutorial-asplos2023

### ISSUE THREAD

**Issue by musigo** [astra-sim/astra-sim#139]
I try to change NPUs to change computation time in exercise_2-2, so i modify network config file dgx2.json, such as
origin file:
`
{
  "dimensions-count": 2,
  "topologies-per-dim": ["Switch", "Switch"],
  "units-count": [16, 16],
  "links-count": [6, 1],
  "link-latency": [500, 500],
  "link-bandwidth": [25, 6.25]
}
`
modified file:
`
{
  "dimensions-count": 2,
  "topologies-per-dim": ["Switch", "Switch"],
  "units-count": [8, 8],
  "links-count": [6, 1],
  "link-latency": [500, 500],
  "link-bandwidth": [25, 6.25]
}
`
I find computation time is same in this two simulation result file.
origin result:
`
Name,TotalTime(us),ComputeTime(us),ExposedCommunicationTime(us),TotalMessageSize(MB)
DGX2-GPT3,787767.340000,**575821.446000**,211945.894000,32943.251953
`
modified result:
`
Name,TotalTime(us),ComputeTime(us),ExposedCommunicationTime(us),TotalMessageSize(MB)
DGX2-GPT3,957884.128000,**575821.446000**,382062.682000,32680.476562
`
I read the code and it doesn't seem to handle the computation time through NPUs.
So, I'm not sure if this branch supports this feature.

**Comment by TaekyungHeo** [comment]
Hello, @musigo.

Thank you for bringing this issue to our attention. You're exploring how adjusting the number of Neural Processing Units (NPUs) in the ASTRA-sim configuration impacts computation time. Based on your experiment's outcomes, it appears that changing the NPUs in the configuration file didn't influence the compute time as expected.

Your observations are indeed aligned with the current capabilities of ASTRA-sim version 1.0. In this version, the simulation framework retrieves pre-calculated compute times and uses them as a static delay, which contributes to the total computation time. As a result, the number of NPUs specified in the configuration file doesn't directly impact the total compute time.

To explore the effects of varying NPUs on computation time more accurately, I'd like to suggest two approaches:
**1. Upgrading to ASTRA-sim 2.0**: This newer version of ASTRA-sim offers enhanced features, such as remote memory models and more sophisticated hierarchical network modeling. Additionally, ASTRA-sim 2.0 utilizes execution traces as input files. These traces are more flexible in terms of workload descriptions and better suited for experiments where workload distribution and NPU utilization are critical factors.

**2. Creating an Execution Trace Generator**: To accurately simulate different NPU configurations, consider developing an execution trace generator. This tool would be responsible for partitioning the workload and assigning tasks to each NPU. By customizing the workload distribution, you can simulate how different numbers of NPUs affect the compute time more realistically.
