### ISSUE TITLE
Questions about the input workload file in Astra-sim 1.0

### ISSUE THREAD

**Issue by XStargate** [astra-sim/astra-sim#152]
> Please provide a detailed description of your question or the information you seek.
Hi,

I'm very curious about the input txt file about workload in Astra-sim 1.0 (like the DLRM_HybridParallel.txt from [https://github.com/astra-sim/astra-sim/blob/master/inputs/workload/ASTRA-sim-1.0/DLRM_HybridParallel.txt](https://github.com/astra-sim/astra-sim/blob/master/inputs/workload/ASTRA-sim-1.0/DLRM_HybridParallel.txt) ). So may I ask you how to generate these workload files based on the given model and parallelism strategies? Is there any tool to generate them?

Thank you so much and any help would be appreciated!

**Comment by willjwon** [comment]
Hi @XStargate,

Excuse my belated response.

Those numbers are generated via analytical calculations. [This slide](https://astra-sim.github.io/assets/tutorials/mlsys-2022/6_mlsys2022_tutorial_Will_demo_exercise_3.pdf), especially slide 11-12, could assist you understand how those workloads are generated. In general, referring to [this tutorial](https://astra-sim.github.io/tutorials/mlsys-2022) can help.

After all, you can represent a workload in ASTRA-sim 1.0 by marking its computation time and communication sizes, if required. The communication size is defined mathematically per the parallelization strategies the workload is assuming. Compute time of each layer can be modeled via various toolchains, including the analytical method shown in this demo, or external tools such as [SCALE-sim](https://github.com/ARM-software/SCALE-Sim), GPU Simulators, or even just measure real GPU communication times.

Hope this helps.
