### ISSUE TITLE
et_converter related problems

### ISSUE THREAD

**Issue by DylanSoren** [astra-sim/astra-sim#153]
When I was using et_converter, the computer reported this error.
![6220430c8bbb1a9fd492372fb0f41d0](https://github.com/astra-sim/astra-sim/assets/76573859/9d867640-cd12-4aa6-ace7-bd9a54e781c6)
what should I do？

**Comment by TaekyungHeo** [comment]
Hello, @DylanSoren,

Please ensure you have cloned the latest astra-sim repository recursively. Try the following command and see if it resolves the issue:

```
git clone --recurse-submodules git@github.com:astra-sim/astra-sim.git
```

**Comment by DylanSoren** [comment]
Thanks for your reply, Chakra project has just fixed the problem.
![Screenshot_20231128_003539](https://github.com/astra-sim/astra-sim/assets/76573859/0248d137-ad23-4dd1-9680-ba0effe18dcd)

**Comment by TaekyungHeo** [comment]
Hello, @DylanSoren,

The PR that you have mentioned will not be accepted by the Chakra project. Please take a look at this comment: https://github.com/mlcommons/chakra/pull/74#issuecomment-1828234221

**Comment by DylanSoren** [comment]
I see. Thank you for your reply.
