### ISSUE TITLE
How to simulate the performance with different types of GPU cards ？

### ISSUE THREAD

**Issue by ysnouyang** [astra-sim/astra-sim#161]
Can astra-sim simulate the impact of GPUs with different computing capabilities/HBM bandwidth/HBM capacity under the same distributed network/scheduling strategy?I haven't seen any input into the capabilities of the GPU itself. 
If it is not currently supported, are there plans to consider supporting it? 
Thank you so much

**Comment by cad-x2** [comment]
Astra-Sim takes the workload as input, the workload input captures the data you are looking for.

The workload data is either generated from real traces (Pytorch) or generated traces from applications like Scale-Sim (https://scalesim-project.github.io/)

**Comment by jinsun-yoo** [comment]
Hi @ysnouyang , ASTRA-sim currently supports two Compute simulators as its Compute modeling backend, from which it defines/takes GPU specific numbers (cycles it takes to compute a specific node, etc.) . 

Please refer to documentation here: https://astra-sim.github.io/astra-sim-docs/compute-backend/compute-backend.html

We are also trying to add a ComputeAPI which will allow users to define their own Compute calculating operations ( #185 ). Thank you!
