### ISSUE TITLE
when convert ASTRA-sim 1.0 gpt3.txt  input files into Chakra traces , get error 'Unsupported parallelism type, HYBRID_TRANSFORMER_FWD_IN_BCKWD'

### ISSUE THREAD

**Issue by CrystalGuo0312** [astra-sim/astra-sim#162]
convert ASTRA-sim 1.0 gpt3.txt input files into Chakra traces with the following commands:
```
python3 -m chakra.et_converter.et_converter \
    --input_type Text \
    --input_filename ../../../inputs/workload/ASTRA-sim-1.0/gpt3.txt \
    --output_filename ../../../inputs/workload/ASTRA-sim-2.0/GPT3 \
    --num_npus 256 \
    --num_dims 1 \
    --num_passes 1
```
got the error 
![image](https://github.com/astra-sim/astra-sim/assets/37615060/75ba9f5f-6342-480e-b198-61e222738e11)
**How to fix it?**

Please give an explanation of the meaning of each number in the first line of the gpt3.txt.
```
HYBRID_TRANSFORMER_FWD_IN_BCKWD	model_parallel_NPU_group: 16 checkpoints: 3 0 9 18 checkpoint_initiates: 3 26 17 8
28											
Q1	-1	9072581	NONE	0	9072581	ALLREDUCE	805306368	9072581	ALLREDUCE	18874368	1
```

**Comment by SallyChangLiu** [comment]
You can see from file extern/graph_frontend/chakra/et_converter/text2chakra_converter.py that the currently supported parallel types are:

- "MICRO"
- "DATA"
- "MODEL"
- "HYBRID_DATA_MODEL"
- "HYBRID_MODEL_DATA"
- "HYBRID_DLRM" or "HYBRID_DLRM_ENHANCED"
And  HYBRID_TRANSFORMER_FWD_IN_BCKWD is not in these parallel types.

**Comment by cad-x2** [comment]
Best way is to start over with Scale-sim, generate a new GPT3 input trace using one of the supported parallel types. 
However the broader issue is that traces from Astra-Sim1 cannot be converted to Astra-sim2 and even if they could, there seems to be other problems with them not finishing
