### ISSUE TITLE
The program cannot finished normally in ASTRA-SIM2.0+NS3

### ISSUE THREAD

**Issue by SallyChangLiu** [astra-sim/astra-sim#164]
## Describe the Bug
> After I modified file extern/graph_frontend/chakra/et_converter/text2chakra_converter.py (I think it's the same bug as mentioned in #158),  the ASTRA-SIM1.0 workload configuration file can generate traffic normally in ASTRA-SIM2.0, but I can not see the `SYS[i] finished` information output when the program ends.

## Steps to Reproduce
> Below is the configuration file I use:

- workload:  inputs/workload/ASTRA-sim-2.0/MLP_HybridParallel_Data_Model
- system: inputs/system/Switch.json
- memory: inputs/remote_memory/analytical/no_memory_expansion.json
- logical_topology: inputs/network/ns3/sample_64nodes_1D.json
- ns3-topology: fat tree (k=8)

**Comment by jinsun-yoo** [comment]
Hi @SallyChangLiu  apologies for the late response. I've checked on my side and confirm that I can see the `Sys[i] finished` option. Could you paste your ns-3 topology file?

**Comment by jinsun-yoo** [comment]
This issue should have been fixed with the recent updates to the NS3 backend. Please feel free to reopen the issue when the problem persists.
