### ISSUE TITLE
Atttribute error in generating traces using chakra.et_converter.et_converter using Docker

### ISSUE THREAD

**Issue by Diksha-Moolchandani** [astra-sim/astra-sim#192]
**python3 -m chakra.et_converter.et_converter --input_type Text --input_filename ../../../inputs/workload/ASTRA-sim-1.0/Resnet50_DataParallel.txt --output_filename ../../../inputs/workload/ASTRA-sim-2.0/Resnet50_DataParallel --num_npus 64 --num_dims 1 --num_passes 1**

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/et_converter.py", line 106, in main
    converter.convert()
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/text2chakra_converter.py", line 147, in convert
    self.convert_data_parallel(f, num_layers)
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/text2chakra_converter.py", line 202, in convert_data_parallel
    self.add_parent(fwd_comp_node, layers[idx-1].fwd_comp_node)
  File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/text2chakra_converter.py", line 136, in add_parent
    child_node.parent.append(parent_node.id)
AttributeError: parent

Kindly help to solve this. Even with docker I am not able to generate the traces.

**Comment by robinren03** [comment]
Could have more information about it. If I manually modify text2chakra_converter.py with the attribute check, I will have
AttributeError: Protocol message Node has no "parent" field.

**Comment by Diksha-Moolchandani** [comment]
this is the solution:  https://github.com/mlcommons/chakra-old/pull/74/commits/8e2f3b4e089c302fdd65a9b183671a5a4ebdfcef

**Comment by Zyx1028** [comment]
Hello, I'm in/usr/local/lib/python3.8 / dist - packages/available/et_def/et_def proto according to your modifications, still hint AttributeError.what I should do?Looking forward to your reply.~

**Comment by Tejanikhil** [comment]
I am also facing the same problem. I have been trying this from past 1 week but couldn't resolve it. 

Traceback (most recent call last):
  File "/home/astra/Desktop/astra-sim/extern/graph_frontend/chakra/et_converter/et_converter.py", line 106, in main
    converter.convert()
  File "/home/astra/Desktop/astra-sim/extern/graph_frontend/chakra/et_converter/text2chakra_converter.py", line 147, in convert
    self.convert_data_parallel(f, num_layers)
  File "/home/astra/Desktop/astra-sim/extern/graph_frontend/chakra/et_converter/text2chakra_converter.py", line 202, in convert_data_parallel
    self.add_parent(fwd_comp_node, layers[idx-1].fwd_comp_node)
  File "/home/astra/Desktop/astra-sim/extern/graph_frontend/chakra/et_converter/text2chakra_converter.py", line 136, in add_parent
    child_node.parent.append(parent_node.id)
AttributeError: 'Node' object has no attribute 'parent

**Comment by Tejanikhil** [comment]
> **python3 -m chakra.et_converter.et_converter --input_type Text --input_filename ../../../inputs/workload/ASTRA-sim-1.0/Resnet50_DataParallel.txt --output_filename ../../../inputs/workload/ASTRA-sim-2.0/Resnet50_DataParallel --num_npus 64 --num_dims 1 --num_passes 1**
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/et_converter.py", line 106, in main converter.convert() File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/text2chakra_converter.py", line 147, in convert self.convert_data_parallel(f, num_layers) File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/text2chakra_converter.py", line 202, in convert_data_parallel self.add_parent(fwd_comp_node, layers[idx-1].fwd_comp_node) File "/usr/local/lib/python3.8/dist-packages/chakra/et_converter/text2chakra_converter.py", line 136, in add_parent child_node.parent.append(parent_node.id) AttributeError: parent
> 
> Kindly help to solve this. Even with docker I am not able to generate the traces.

The reason why you are facing this error is that there are issues with the connection of submodules with their corresponding repos. You can resolve this error just by replacing the ``**child_node.parent.append()**`` with ``**child_node.data_deps.append()**``. Because the child_node doesnot have the attribute named parent in the et_def_pb2
