### ISSUE TITLE
Not Compatible with the latest Chakra

### ISSUE THREAD

**Issue by liecn** [astra-sim/astra-sim#193]
## Describe the Bug
> A clear and concise description of what the bug is.

Hi,

Thank you for your excellent work.

I've discovered that the latest version of Astra-sim is not compatible with the latest version of Chakra. Specifically, Chakra has been reorganized, but Astra-sim is still using the old structure.

**Comment by cshuawei** [comment]
Hi! I am facing a similar issue. Has the problem been fixed? If so, what are the commits for the compatible versions. Thanks!

**Comment by csh27** [comment]
Hi! I am running into a similar issue. Were you able to get past the problem? If so, what commit ids work? Thanks
