### ISSUE TITLE
Compile & Link failed on Ubuntu 24.04

### ISSUE THREAD

**Issue by HeRaNO** [astra-sim/astra-sim#220]
## Describe the Bug

When compiling the project following [the instruction](https://astra-sim.github.io/astra-sim-docs/getting-started/installing-astra-sim.html) on Ubuntu 24.04, it fails because `uint64_t` needs header file `cstdint` included on GCC 13.2.0.

But after change the G++ version to 11.4.0, it fails on linking protobuf dynamic libraries.

![YUJGSD}3PA66 O9}EOXTSQG](https://github.com/user-attachments/assets/48db0be8-5519-4205-b68e-cff918e87106)

But on Ubuntu 22.04, it is OK. So maybe we rely on an older version of libprotobuf? I'm not sure but we need to note this in the build guide.

## System Info

- OS: Ubuntu 24.04
- G++ Version: GCC 13.2.0 / 11.4.0

**Comment by jinsun-yoo** [comment]
Hi @HeRaNO thanks for reporting this issue. Solved with #235. Closing.
