### ISSUE TITLE
Simulation broken when chakra_convert using `Text` mode

### ISSUE THREAD

**Issue by HeRaNO** [astra-sim/astra-sim#222]
I have tried to run astra-sim 2.0 with NS3 in the past few days. I used Resnet50_DP workload and default configuration, but the simulation has been running for three days and it's still not finished, and no QP finished. It hung with:

```plain
ASTRA-sim + NS3
There are 8 npus: 8,
ring of node 0, id: 0 dimension: local total nodes in ring: 8 index in ring: 0 offset: 1total nodes in ring: 8
ring of node 0, id: 0 dimension: local total nodes in ring: 8 index in ring: 0 offset: 1total nodes in ring: 8
ring of node 0, id: 0 dimension: local total nodes in ring: 8 index in ring: 0 offset: 1total nodes in ring: 8
ring of node 0, id: 0 dimension: local total nodes in ring: 8 index in ring: 0 offset: 1total nodes in ring: 8
QP is enabled 
maxRtt=2040 maxBdp=102000
here
sys[0] finished, 1082450000 cycles
sys[1] finished, 1082450000 cycles
sys[2] finished, 1082450000 cycles
sys[3] finished, 1082450000 cycles
sys[4] finished, 1082450000 cycles
sys[5] finished, 1082450000 cycles
sys[6] finished, 1082450000 cycles
sys[7] finished, 1082450000 cycles
<running...>
```

So how long will it take to run NS-3 simulation with astra-sim 2.0? Or did I make a wrong configuration? My configuration is:

```bash
# build.sh
WORKLOAD="${SCRIPT_DIR:?}"/../../inputs/workload/ASTRA-sim-2.0/Resnet50_DataParallel # (64 files download from runs/example/workload/download.sh)
SYSTEM="${SCRIPT_DIR:?}"/../../inputs/system/Switch.json # remain unchanged
MEMORY="${SCRIPT_DIR:?}"/../../inputs/remote_memory/analytical/no_memory_expansion.json # remain unchanged
LOGICAL_TOPOLOGY="${SCRIPT_DIR:?}"/../../inputs/network/ns3/sample_8nodes_1D.json # remain unchanged
# Note that ONLY this file is relative to NS3_DIR/simulation
NETWORK="../../../ns-3/scratch/config/config.txt"
```

```plain
// NS3 config, all remain unchanged
TOPOLOGY_FILE ../../scratch/topology/8_nodes_1_switch_topology.txt
FLOW_FILE ../../scratch/output/flow.txt
TRACE_FILE ../../scratch/output/trace.txt
TRACE_OUTPUT_FILE ../../scratch/output/mix.tr
FCT_OUTPUT_FILE ../../scratch/output/fct.txt
PFC_OUTPUT_FILE ../../scratch/output/pfc.txt
QLEN_MON_FILE ../../scratch/output/qlen.txt
```

**Comment by HeRaNO** [comment]
It seems that the workload files do not cope with the simulator, resulting in no flow present in the simulation. When I change the workload to #176 mentioned, it runs well. So maybe it's a bug.

Changing `LOGICAL_TOPOLOGY` to 64nodes ones does not help.

**Comment by jhkjames1110** [comment]
I've had the same issue. The above code running is not an accurate simulation because it doesn't even simulate the communication nodes properly. Check the Workload.cc file and you can find that the communication operation should call issue_comm, but it doesn't because is_cpu_only is set to TRUE by default in et_feeder_node.cpp. 
I am not sure if this is a problem with the trace (as it did not specify the is_cpu_only field in its attributes) or if it is the problem with the et_feeder_node.cpp.

**Comment by HeRaNO** [comment]
The `et` file between Resnet50 (`Text` mode) and Megatron (`PyTorch` mode, probably) made by `chakra_convert` are quite different. I'm not sure if the file converted in `Text` mode is broken.

Let's try DLRM trace in `param/train/compute/python/test/data`

**Comment by HeRaNO** [comment]
> Let's try DLRM trace in `param/train/compute/python/test/data`

It runs pretty well. So change the title.

**Comment by jhkjames1110** [comment]
How did you get the .et files for the DLRM example? I only see .json files.

**Comment by jhkjames1110** [comment]
> It runs pretty well. So change the title.

Does your simulation finish (exits out properly) or does it just hang like in the first issue post?

**Comment by HeRaNO** [comment]
> How did you get the .et files for the DLRM example? I only see .json files.

I followed the instruction [here](https://github.com/mlcommons/chakra/wiki/Running-Simulation-with-Chakra#using-chakra-execution-trace-and-kineto-traces-generated-by-pytorch), and I get the DLRM trace from the specific commit of param (same as the astra included as a submodule), you can check [here](https://github.com/facebookresearch/param/tree/fd5ad3aae7bfe6a28db7b0070a5135b359a8d4c0/train/compute/python/test/data) two get the two parts of trace.

> Does your simulation finish (exits out properly) or does it just hang like in the first issue post?

Yes, it exits properly. But with a slight change. [Here](https://github.com/astra-sim/astra-sim/blob/master/astra-sim/network_frontend/ns3/AstraSimNetwork.cc#L273) should set stop time before running start. And I change the stop time to 1s. It can stop properly. If you set a huge stop time, it will hang because `monitor_buffer` will be called every 100ns. Stop at 1s may be a good choice, probably.

**Comment by HeRaNO** [comment]
It's the same issue as #224, so let's wait for that one.

**Comment by tninth** [comment]
> 我遇到了同样的问题。上述代码运行并不是一个准确的模拟，因为它甚至没有正确模拟通信节点。检查 Workload.cc 文件，您会发现通信操作应该调用 issue_comm，但实际上没有，因为 is_cpu_only 在 et_feeder_node.cpp 中默认设置为 TRUE。我不确定这是跟踪的问题（因为它没有在其属性中指定 is_cpu_only 字段）还是et_feeder_node.cpp的问题。
> 
> 我尝试删除 is_cpu_only=true 行并输入 is_cpu_only=false，它给了我一个 Segmentation Error。这个项目需要一个 wiki。

Hello, is this problem solved now?
