### ISSUE TITLE
Clarification Needed for Collective Communication Description

### ISSUE THREAD

**Issue by yue2388253** [astra-sim/astra-sim#226]
> Please provide a detailed description of your question or the information you seek.

First, I want to express my gratitude for the fantastic work you are doing with Astra-sim. It’s an invaluable tool for the community!

As I am new to the community, I hope I’m not overwhelming you with questions, and I apologize if my observations seem obvious. While reviewing the documentation, I noticed that the description of collective communication in the comments may have some inaccuracies. After checking the related paper ([1] Fig. 8), I wonder if the correct description might be as follows:

![image](https://github.com/user-attachments/assets/a118b9cc-ef6f-46d2-a096-320553742c02)

## References:

[1] Won, William, et al. "LIBRA: Enabling Workload-aware Multi-dimensional Network Topology Optimization for Distributed Training of Large AI Models." 2024 IEEE International Symposium on Performance Analysis of Systems and Software (ISPASS). IEEE, 2024.

**Comment by jinsun-yoo** [comment]
Hi @yue2388253 , thank you for pointing this out! Yes, your observation is correct. I will adjust the documentation.

**Comment by jinsun-yoo** [comment]
Solved with #239
