### ISSUE TITLE
Compilation Failure After Latest PR Merge - Missing et_feeder.h

### ISSUE THREAD

**Issue by yue2388253** [astra-sim/astra-sim#246]
## Describe the Bug
> A clear and concise description of what the bug is.

Hi, 

I am experiencing a compilation failure after fetching the newest version. It seems that the GitHub Actions workflow is also failing with the same error.

Here is the error message:

```
In file included from /home/runner/work/astra-sim/astra-sim/astra-sim/system/RecvPacketEventHandlerData.hh:11,
                 from /home/runner/work/astra-sim/astra-sim/astra-sim/system/StreamBaseline.hh:13,
                 from /home/runner/work/astra-sim/astra-sim/astra-sim/system/BaseStream.cc:8:
/home/runner/work/astra-sim/astra-sim/astra-sim/system/collective/ChakraImpl.hh:15:10: fatal error: extern/graph_frontend/chakra/et_feeder/et_feeder.h: No such file or directory
   15 | #include "extern/graph_frontend/chakra/et_feeder/et_feeder.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Thank you for your assistance!

Best regards,

**Comment by beatlesforever** [comment]
Hi,

I encountered the same issue before merging the latest PR. You might want to try using the HotI 2024 version (https://astra-sim.github.io/tutorials/hoti-2024/installation#starting-docker-container). I was able to successfully compile with that version.

Hope this helps!

**Comment by jiahengxiong** [comment]
I meet the same issue. It makes me so sad.

**Comment by beatlesforever** [comment]
> I meet the same issue. It makes me so sad.

Hello, do you know if the compilation error has been resolved?

**Comment by beatlesforever** [comment]
Hello, do you know if the compilation error has been resolved?

**Comment by yue2388253** [comment]
This issue has been resolved.
