### ISSUE TITLE
How to generate workload of Resnet50

### ISSUE THREAD

**Issue by fanfancy** [astra-sim/astra-sim#34]
I used the im2col function to calculate the mnk value of each layer and then used the scripts "scripts/workload_generator/gen_astrasim_workload_input.py" to generate the workload. The generated workload file is different with the given "Resnet50_DataParallel.txt". Especially, the computation time of "fwd_pass", "inp_grad" and "wgt_grad" are the same for one layer in the generated workload.

The given workload of resnet50 in "Resnet50_DataParallel.txt":
![image](https://user-images.githubusercontent.com/22411991/101112627-b775d580-3618-11eb-8da5-26b15d28d8d9.png)

The mnk file I used is as follows, the input size of picture is set to 224*224*3:
![image](https://user-images.githubusercontent.com/22411991/101112892-4387fd00-3619-11eb-8b9d-9c84a4772af4.png)

My generated workload of resnet50:
![image](https://user-images.githubusercontent.com/22411991/101112690-dd02df00-3618-11eb-9c50-269d2e3e3870.png)

The config of tpu i used is the default "google.cfg".
`[general]
run_name = "GoogleTPU_os"

[architecture_presets]
ArrayHeight:    256
ArrayWidth:     256
IfmapSramSz:    8192
FilterSramSz:   8192
OfmapSramSz:    8192
IfmapOffset:    0
FilterOffset:   10000000
OfmapOffset:    20000000
Dataflow:       os
`

I will be very appreciated if you could give me some suggestion.

**Comment by fanfancy** [comment]
The config in "gen_astrasim_workload_input.py" is set to :
![image](https://user-images.githubusercontent.com/22411991/101113334-1f78eb80-361a-11eb-88b5-96ffbff55514.png)

**Comment by rashidi1saeed** [comment]
Hi @fanfancy. Thanks for your interest in our tool and for reporting your issue. The reason for the different compute results You got for Resnet is that in the default "Resnet50_DataParallel.txt", we used a different compute simulator. So your results  are fine. Also the reason for the communication difference is because we used FP32 for this workload while you probably used FP16.  Let me know if you have further questions.

**Comment by fanfancy** [comment]
Hello@rashidi1saeed, I got it. Thank you very much for your reply.  : )

**Comment by aakash-sharma** [comment]
@fanfancy Do you mind releasing your im2col script to calculate mnk values for each layer?

**Comment by tangyuelm** [comment]
Dear Authors and @fanfancy,

I just installed astra-sim and ran it following the instructions. I am also interested in how to generate workloads for CNN models, but It seems that the "scripts/workload_generator/gen_astrasim_workload_input.py" is not in the installation package. I have attached the screenshot of the hierarchy of the installed files. Could you please let me know where to find these codes? If it requires other installation, would it be possible to provide any instructions? Thank you.
![image](https://github.com/astra-sim/astra-sim/assets/58452529/63167fab-3140-4ac7-82f1-59bff05db8ec)
