### ISSUE TITLE
Using multithreading to improve astra-sim simulation times.

### ISSUE THREAD

**Issue by vinodganesan** [astra-sim/astra-sim#36]
Is there a way to enable multi-core Astra-sim simulations to improve the runtime of the simulation? If yes, how to enable it? 
If not, are there plans to support it?

**Comment by rashidi1saeed** [comment]
Hi @vinodganesan , there is a plan to add multithreading support in the future. This happens after the compatible NS3 backend is released and we are planning to enable this for the AstraSIM+NS3 integration in the future.

**Comment by vinodganesan** [comment]
Thank you for the comment, @rashidi1saeed.
