### ISSUE TITLE
Reg. support for communication topologies in addition to Torus 3/4/5D, AlltoAll, NV_Switch

### ISSUE THREAD

**Issue by vinodganesan** [astra-sim/astra-sim#38]
Hi,

I was trying to use Astra-Sim with other communication topologies such as Mesh_XY, Ring, and Cluster. But I figured that the parser is not looking for variables associated with those topologies like mesh-rows, link-latency, package-cols, etc. (https://github.com/georgia-tech-synergy-lab/gem5_astra/blob/73541b0e3cb702bb7957931a8038fc923382bbd5/configs/network/Network.py#L36) 

But even after adding those terms to the parser, I get a segfault with some "package_cols > 0" assertion. 
Upon digging deeper, it looks like only Torus 3/4/5D and AlltoAll/NVSwitch are being supported (https://github.com/georgia-tech-synergy-lab/gem5_astra/blob/73541b0e3cb702bb7957931a8038fc923382bbd5/src/mem/ruby/network/garnet2.0/NetworkInterface.cc#L110-L125)

Although I haven't gone through the entire codebase as it is exhaustive, this is my informed assumption based on my understanding of the parts of codes I have mentioned above. 

Am I correct to assume that astra-sim doesn't currently support all the topologies that garnet-2.0 supports? If not, what am I missing, and what should I do to enable that?  

Let me know if you need me to share the segfault log, the network input files used for mesh topology, and the additions I had made to the code to enable the parsing of Mesh_XY.

Thanks,
Vinod

**Comment by TravisDai** [comment]
Hi Vinod, have you solved it?

**Comment by tushar-krishna** [comment]
The garnet backend for astra-sim only supports topologies for which topology-aware collectives exist (hence ring, torus, switch, and alltoall). For now the garnet backend is not being actively used/maintained, so closing this issue.
