### ISSUE TITLE
ERROR in compiling & running Garnet2.0 as the network simulator 

### ISSUE THREAD

**Issue by daitr616** [astra-sim/astra-sim#39]
When using "./build/astra_garnet/build.sh -c" I met following errors:

scons: *** [build/Garnet_standalone/arch/alpha/generated/generic_cpu_exec.o] Error 1
scons: building terminated because of errors.
cp: cannot stat '/home/travis/Documents/astra-sim/build/astra_garnet/../../extern/network_backend/garnet/gem5_astra/build/Garnet_standalone/gem5.opt': No such file or directory

**Comment by HamHyungkyu** [comment]
Did you solved it?

**Comment by TravisDai** [comment]
Yes, you need to compile the gem5 to obtain gem5.opt
