### ISSUE TITLE
Accept Path to Input Files as Input

### ISSUE THREAD

**Issue by steinbrecher** [astra-sim/astra-sim#4]
Right now, Astra-SIm assumes that inputs are at a specific location relative to where the binary is being run -- [for example, here](https://github.com/astra-sim/astra-sim/blob/master/astra-sim/system/Sys.cc#L1149). Let's fix that by accepting this as an input when you instantiate the relevant class(es)

**Comment by rashidi1saeed** [comment]
> Right now, Astra-SIm assumes that inputs are at a specific location relative to where the binary is being run -- [for example, here](https://github.com/astra-sim/astra-sim/blob/master/astra-sim/system/Sys.cc#L1149). Let's fix that by accepting this as an input when you instantiate the relevant class(es)

I add a fix that if in the workload and system input directories (that we provide as an input to astra-sim), there is '/' character, then astra-sim interprets this as an absolute path and search that directory and filename (e.g. "/usr/.../microAllReduce"), otherwise, it tries to search the binary location path to find the "workload_inputs" and "sys_inputs" folders and search those folders for system and workload input files (e.g. "microAllReduce"). Does that solve the issue?

**Comment by steinbrecher** [comment]
Saeed,

Where are you thinking of putting this logic? 

I think a key, important point is that this kind of file discovery logic shouldn't be living inside of Sys or Workload -- path discovery etc. should be a _top level_ consideration. That is, if I'm instantiating a bunch of Sys and Workload objects, I should be able to (in fact, required to) pass them the full path to the workload files. 

Any other behavior (including special handling based on the presence of a "/" in the filename) violates the principle of least surprise -- I expect that when I give an API a filename / path to a file, that it treats that as the explicit path, and then fails if it can't find that file. 

Does that make sense? The big picture here is getting some of the management logic out of the core of Astra-Sim and into the calling code -- as a user, I want Astra-Sim to do what it does best, and let other libraries/ functions deal with things like file discovery.

**Comment by steinbrecher** [comment]
Ah, I see that you pushed the change in [this commit](https://github.com/astra-sim/astra-sim/commit/9693752743089e8e1e76d3f2348161257fe4cccf) -- it would be better to have made this a pull request so we could discuss the before it was merged. Let's use that workflow from now on?

**Comment by rashidi1saeed** [comment]
> Saeed,
> 
> Where are you thinking of putting this logic?
> 
> I think a key, important point is that this kind of file discovery logic shouldn't be living inside of Sys or Workload -- path discovery etc. should be a _top level_ consideration. That is, if I'm instantiating a bunch of Sys and Workload objects, I should be able to (in fact, required to) pass them the full path to the workload files.
> 
> Any other behavior (including special handling based on the presence of a "/" in the filename) violates the principle of least surprise -- I expect that when I give an API a filename / path to a file, that it treats that as the explicit path, and then fails if it can't find that file.
> 
> Does that make sense? The big picture here is getting some of the management logic out of the core of Astra-Sim and into the calling code -- as a user, I want Astra-Sim to do what it does best, and let other libraries/ functions deal with things like file discovery.

Yes this makes sense, I pushed a fix, and right now all system and workload input names are considered to be the explicit paths.

**Comment by rashidi1saeed** [comment]
Issue solved
