### ISSUE TITLE
Incompatible types concatenation in Layers.print()

### ISSUE THREAD

**Issue by AnandS09** [astra-sim/astra-sim#41]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/5242812/118870949-17092a00-b8b5-11eb-9331-947171a8db2b.png">

File: astra_sim/scripts/workload_generator/gen_astrasim_workload_input.py

Print() method tries to concatenate int with string.

**Comment by AnandS09** [comment]
The fix for this is pushed in PR #42

**Comment by rashidi1saeed** [comment]
This is addressed!
