### ISSUE TITLE
got "control reaches end of non-void function -werror=return-type" when compiling GEM-5

### ISSUE THREAD

**Issue by ZhenlongMa** [astra-sim/astra-sim#52]
I ran `python2 /usr/bin/scons build/X86/gem5.opt -j5` in extern/network_backend/garnet/gem5_astra, and got an error message got `control reaches end of non-void function -werror=return-type`. 
Finally I found that function `Sys::get_priority(SchedulingPolicy pref_scheduling)`  in `extern/network_backend/garnet/gem5_astra/build/X86/mem/ruby/network/garnet2.0/astra-sim/system/Sys.cc` ended without else return, so I changed it as:
```
int Sys::get_priority(SchedulingPolicy pref_scheduling) {
  if (pref_scheduling == SchedulingPolicy::LIFO) {
    return priority_counter++;
  } else if (pref_scheduling == SchedulingPolicy::FIFO) {
    return priority_counter--;
  } else if (pref_scheduling == SchedulingPolicy::HIGHEST) {
    return 100000000;
  } else if (pref_scheduling == SchedulingPolicy::None) {
    if (scheduling_policy == SchedulingPolicy::LIFO) {
      return priority_counter++;
    } else {
      return priority_counter--;
    }
    // added by Zhenlong Ma
  } else {
    return -1;
  }
}
```
I don't know if this will bring unexpected effect, please figure it out if I made it wrong, thanks!

**Comment by rashidi1saeed** [comment]
Hi @ZhenlongMa , 
Thanks for your comment. In reality, it never reaches that else condition you added. So, the code runs as expected whether or not you add the else statement. We will fix this in the next update
