### ISSUE TITLE
Error when running run_sim.sh

### ISSUE THREAD

**Issue by ZhenlongMa** [astra-sim/astra-sim#57]
I ran `./run_sim.sh -n garnet -s sample_a2a_sys.txt -w Resnet50_DataParallel.txt`, and got `./run_sim.sh: Line 55: 17484 Segment Fault              (Core Dump) .....`. I am not sure why this happened. Can you run this command successfully? Thanks!

**Comment by rashidi1saeed** [comment]
Hi @ZhenlongMa , we will investigate this and will get back to you shortly in next few days

**Comment by rashidi1saeed** [comment]
Hi @ZhenlongMa , if you look at the run_sim.sh script, the network layer input for garent backend is: **sample_torus.txt**, which is basically a 3D torus. So you have to pick a **system layer input** that is tuned for such torus 3D. Therefore, if you change your command to this: 
./run_sim.sh -n garnet **-s sample_torus_sys.txt** -w Resnet50_DataParallel.txt

your run works OK. If you look at the current "sample_a2a_sys.txt" system input file, it is basically defining collectives for a 1D plain alltoall(fully connected) physical topology. So, when choosing a 3D physical topology (i.e., 3D torus) ASTRASIM cannot know what to do for 2'nd dim and 3'rd dim of your physical 3D torus if you select "sample_a2a_sys.txt" as system layer.

**Comment by rashidi1saeed** [comment]
let me know if you have any further questions
