### ISSUE TITLE
Validity of link latency parameters

### ISSUE THREAD

**Issue by sylee0124** [astra-sim/astra-sim#59]
Hello, I have question about the link latency value used in one of your tutorials (Exercise 3: Comparing Systems)
There, 500ns was used for link latency of nvlink in DGX-2. 
Is this a valid number? If so can you share some reference?

Thanks.

**Comment by rashidi1saeed** [comment]
Hi @sylee0124 ,

NVLink latency parameters are confidential and not public. Our estimation of NVLink latency is based form some measurements that are also reported in this paper:
https://ieeexplore.ieee.org/abstract/document/9188288

However, I can refer you to this paper that did some studies on Nvlink latencies (page 3):
https://arxiv.org/abs/2111.04867
This paper assumes 700 ns for NVLink (on NDv2 platform) step latency.

**Comment by sylee0124** [comment]
Thank you for your kind response @rashidi1saeed !!
