### ISSUE TITLE
How to generate workloads for Resnet50 and other DNN models(For example,alexnet)？

### ISSUE THREAD

**Issue by hyperliuxue** [astra-sim/astra-sim#61]
Hi, recently I tried to use "gen_astrasim_workload_input.py" to generate "Resnet50_DataParallel.txt"，But I had some problems, as covered in the issue#34(https://github.com/astra-sim/astra-sim/issues/34).

If I want to generate the same or similar data as "Resnet50_DataParallel.txt", as you have provided，would you like to release the relevant  compute simulator?
I would be grateful if you could help me with my needs!

**Comment by TaekyungHeo** [comment]
Hello, @hyperliuxue  ,

Thanks for your question. In ASTRA-sim 1.0, there is indeed a  workload generator that allows you to create workloads with arbitrary M, N, K dimensions for convolutional networks like ResNet50.

However, we highly recommend using ASTRA-sim 2.0, which offers enhanced features such as remote memory API and hierarchical network modeling, and also includes several bug fixes. While ASTRA-sim 2.0 does not have a direct script for M, N, K generation, it allows for more flexible and descriptive workload definitions which can aid in setting up your convolutional network simulations more effectively.

Please let us know if you encounter any issues or have questions about defining workloads in ASTRA-sim 2.0, and we will be glad to assist you.
