### ISSUE TITLE
Suspected Bug in Sys.cc

### ISSUE THREAD

**Issue by G-alois** [astra-sim/astra-sim#62]
I found this suspected bug when I use it for simulation which has a large scale of comm_size. The data type of the value returned by the function _determine_chunk_size_ seems  to be in conflict with that defined in this function. (line 996-999, astra-sim/astra-sim/system/Sys.cc, as well as in the line 323 of Sys.hh)
I will really appreciate it if you can fix it.

**Comment by rashidi1saeed** [comment]
Hi @G-alois ! Thanks a lot for catching the bug. We have fixed it in the new commit!

**Comment by G-alois** [comment]
> Hi @G-alois ! Thanks a lot for catching the bug. We have fixed it in the new commit!

Thank you for your reply as well as so much help you offered me before!
