### ISSUE TITLE
Suggestion for a unified clone version for different branches of astra-sim 

### ISSUE THREAD

**Issue by G-alois** [astra-sim/astra-sim#63]
When I use git-clone of astra-sim, the content of files in astra-sim/analytical seems to be different with different branches. Take  NetworkConfigParser.cc(astra-sim/analytical/src/helper/NetworkConfigParser.cc) as an example,  the old version uses 'T', 'N', 'P', 'PP'(line55-68), while the version in the branch of tutorials uses 'Tile', 'Package', 'Node', 'Pod'(line 62-74). I think unifying the versions under these branches will be better for users.
I will really appreciate it if you can adopt my advice.

**Comment by G-alois** [comment]
By the way, there is a spelling mistake in this link _https://github.com/astra-sim/astra-sim/tree/master/astra-sim/system_. The word _manages_ turns to be _maanages_.

**Comment by G-alois** [comment]
There is another spelling mistake in this link _https://github.com/astra-sim/astra-sim/tree/master/astra-sim/workload_. The word _examples_ turns to be _eamples_.

**Comment by TaekyungHeo** [comment]
Thanks for your suggestion and sorry for the delayed response. We're currently working on tidying up ASTRA-sim's codebase, including unifying versions across different branches. These updates will be rolled out in the next few weeks.

**Comment by G-alois** [comment]
Many thanks!

Best Regards,
Le Qin

发件人: Taekyung Heo ***@***.***>
发送时间: 2023年7月13日 0:41
收件人: astra-sim/astra-sim ***@***.***>
抄送: Le QIN ***@***.***>; Author ***@***.***>
主题: Re: [astra-sim/astra-sim] Suggestion for a unified clone version for different branches of astra-sim (Issue #63)

你通常不会收到来自 ***@***.******@***.***> 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

Thanks for your suggestion and sorry for the delayed response. We're currently working on tidying up ASTRA-sim's codebase, including unifying versions across different branches. These updates will be rolled out in the next few weeks.
