### ISSUE TITLE
"address-of-packed-member" warning

### ISSUE THREAD

**Issue by hanskasan** [astra-sim/astra-sim#7]
I ran into this issue when trying to build the garnet network simulator (step 3).

`build/Garnet_standalone/base/inet.hh:355:45: error: taking address of packed member of 'ip_opt' may result in an unaligned pointer value [-Werror=address-of-packed-member] `

Is this a warning that I can ignore? If it has to be fixed, can you please provide a way to fix it?

Thank you.

**Comment by rashidi1saeed** [comment]
> I ran into this issue when trying to build the garnet network simulator (step 3).
> 
> `build/Garnet_standalone/base/inet.hh:355:45: error: taking address of packed member of 'ip_opt' may result in an unaligned pointer value [-Werror=address-of-packed-member] `
> 
> Is this a warning that I can ignore? If it has to be fixed, can you please provide a way to fix it?
> 
> Thank you.

Hi , Have you installed all packages necessary to build gem5? If yes, then please ignore this and try to build it? let me know of during the run-time you are facing issues

**Comment by hanskasan** [comment]
Hi,
I tried to rebuild this in Ubuntu (previously tried to build it in CentOS and got the "address-of-packed-member" warnings). It's now working great but I have to ignore "maybe-uninitialized" warnings.
Thanks!
