### ISSUE TITLE
Generate mnk for resnet50 and conv nets in general

### ISSUE THREAD

**Issue by aakash-sharma** [astra-sim/astra-sim#70]
Hello - could you please let me know how do you generate the mnk file for a conv net like resnet50? I couldnt find and script to generate mnk values for convolution parameters.
Basically in convolution, input, output as well as filters have 4 dimensions. How do i convert it to mnk ?

**Comment by TaekyungHeo** [comment]
Hello, @aakash-sharma ,

Thanks for your question. In ASTRA-sim 1.0, there is indeed a script for the workload generator that allows you to create workloads with arbitrary M, N, K dimensions for convolutional networks like ResNet50.

However, we highly recommend using ASTRA-sim 2.0, which offers enhanced features such as remote memory API and hierarchical network modeling, and also includes several bug fixes. While ASTRA-sim 2.0 does not have a direct script for M, N, K generation, it allows for more flexible and descriptive workload definitions which can aid in setting up your convolutional network simulations more effectively.

Please let us know if you encounter any issues or have questions about defining workloads in ASTRA-sim 2.0, and we will be glad to assist you.
