### ISSUE TITLE
Question about boost-mode

### ISSUE THREAD

**Issue by xiangchenwu** [astra-sim/astra-sim#71]
`bool enabled = !boost_mode;
if (id % total_nodes == 0 && id < total_nodes * physical_dims[current_dim]) {
        enabled = true;
      }
      if (!enabled) {
        total_disabled += queues_per_dim[current_dim];
      }`
I don't know about the handling of boost-mode parameter, can you explain in detail?
Thanks in advance

**Comment by TaekyungHeo** [comment]
To enable boost-mode, set "boost-mode:" to 1 in the system configuration file ([link](https://github.com/astra-sim/astra-sim/blob/07d5d19de827d77890c0c02850f5bcf78bf6ba45/inputs/system/sample_3dim_sys.txt#L5C1-L5C14)). The boost-mode is designed to enhance simulation performance by simulating a single node in a multi-GPU system, assuming that all GPUs are executing the same operation.
