### ISSUE TITLE
can i adjust the computing performance for each NPU？

### ISSUE THREAD

**Issue by tyn513** [astra-sim/astra-sim#73]
can i adjust the computing performance for each NPU？

**Comment by TaekyungHeo** [comment]
In ASTRA-sim 2.0, you can set the performance for all NPUs collectively using the roofline model. However, the ability to adjust the performance for each NPU individually is not currently supported. To implement this feature, you could modify the initialization phase to have different performance numbers for each NPU. Hope this helps!

**Comment by TaekyungHeo** [comment]
In ASTRA-sim 2.0, you can set the performance for all NPUs collectively using the roofline model. However, the ability to adjust the performance for each NPU individually is not currently supported. To implement this feature, you could modify the initialization phase to have different performance numbers for each NPU. Hope this helps!
