### ISSUE TITLE
An error about event time

### ISSUE THREAD

**Issue by yunruowu** [astra-sim/astra-sim#74]
The error message：
/astra-sim/extern/network_backend/analytical/analytical/event-queue/EventQueue.cc:20: void Analytical::EventQueue::add_event(AstraSim::timespec_t, void (*)(void*), void*): Assertion `EventQueueEntry::compare_time_stamp(current_time, time_stamp) < 0' failed.
What should I do for this?

**Comment by TaekyungHeo** [comment]
Hello @yunruowu, could you please provide more detailed information to reproduce the error?
