### ISSUE TITLE
in-network collective offload support

### ISSUE THREAD

**Issue by yunruowu** [astra-sim/astra-sim#76]
How ues this feature in the ASTRA-SIM

**Comment by TaekyungHeo** [comment]
Hello @yunruowu ,

At the moment, the in-switch collective communication feature is not yet available. Originally, this feature was implemented for a specific memory architecture within the memory model. However, we've expanded its capabilities so it can model any networked systems. The feature itself is ready to go, but we're currently devoting our efforts to refining and tidying up the codes. Once we've polished the codes, we will be ready to launch this feature.

Stay tuned for our project updates :) Your interest and patience are highly appreciated.
