### ISSUE TITLE
The network backend NS3 under branch ns3_interface_tmp2 is not available

### ISSUE THREAD

**Issue by CavalryXD** [astra-sim/astra-sim#88]
The NS3 interface under branch **ns3_interface_tmp2** is not available. I check the github link: https://github.com/DartingMelody/ns3-interface, in which the repo is not open.
I wonder to know when the NS3 backend is available.

**Comment by jinsun-yoo** [comment]
Hi @CavalryXD, We migrated the repo into https://github.com/astra-sim/astra-network-ns3. The repo is public and should be visible now. 
We are currently testing to verify the migrated repository works, and will respond in a few days.

**Comment by jinsun-yoo** [comment]
Hi @CavalryXD, sorry for the late follow up. You should be able to use the new repo right now. Please feel free to report any questions you may have along the way!
