### ISSUE TITLE
Fail to exetute the build script:

### ISSUE THREAD

**Issue by tangyuelm** [astra-sim/astra-sim#93]
Dear Authors,

Thank you for the tool. I am trying to install the tool and run it on my local computer but got an error in the following processes of the 1st step.
# For the analytical network backend
$ ./build/astra_analytical/build.sh -c
The error is shown in the screenshot. Would it be possible to provide any help? Thank you.
![image](https://github.com/astra-sim/astra-sim/assets/58452529/b19c8728-e116-4a9d-958d-e22f9c06fa4a)

**Comment by SallyChangLiu** [comment]
before this installing protobuf will be helpful

**Comment by tangyuelm** [comment]
Thank you for the advice. However, protobuf is already installed. I am wondering if there is a requirement for the operation system. Currently, I am using ubuntu 18.04.5 lts（gnu/linux 5.4.72-microsoft-standard-wsl2 x86_64, the linux subsystem from Win10. After I installed cmake and other required libs, I met an error that "cmake 3.15 or higher is required.  you are running version 3.10.2", so I reinstalled the latest cmake which is  3.25.2. Does it matter?


![image](https://github.com/astra-sim/astra-sim/assets/58452529/35c18f4d-9749-44f6-87a5-a49dd29b88d3)

**Comment by tangyuelm** [comment]
The configuration of my environment is as follows
![image](https://github.com/astra-sim/astra-sim/assets/58452529/75dbf2af-3eac-42a6-b7ef-3329cec66b95)

**Comment by TaekyungHeo** [comment]
Have you had the opportunity to follow the instructions in the README file? Did you install all the required packages mentioned in the README? Here's the list for reference:
```
$ sudo apt-get -y install\
    gcc g++ make cmake\
    libboost-dev libboost-program-options-dev\
    libprotobuf-dev protobuf-compiler\
    python3 python3-pip git
$ sudo pip3 install protobuf==3.6.1 pydot
```

**Comment by tangyuelm** [comment]
Thank you for the advice. I am sure I followed the instructions. However, during the previous installation, it reported an error that my cmake version was lower than 3.15, so I updated it to 3.25. I also double-checked other packages and the versions are as follows.
![image](https://github.com/astra-sim/astra-sim/assets/58452529/16ace59f-a94c-4b79-803b-5eab216aefd8)
![image](https://github.com/astra-sim/astra-sim/assets/58452529/f7b250ae-a136-4413-adb2-cb6679946f1a)
![image](https://github.com/astra-sim/astra-sim/assets/58452529/e667f979-11d0-4404-b0b5-d9a90593e317)

**Comment by TaekyungHeo** [comment]
Do you still see the same error? (missing port_def.inc)

**Comment by tangyuelm** [comment]
Yes. The problem is still there.

**Comment by tangyuelm** [comment]
I used ubuntu 22.04 wsl and now the tool can run successfully.

**Comment by TaekyungHeo** [comment]
Cool, good to know that!

**Comment by Saeeedd** [comment]
I have the same problem. Could anyone help me solve this on Ubuntu 20.04?
